//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SAL.EFLib
{
    public partial class Agreement
    {
        public int ROW_ID { get; set; }
        public int CustomerID { get; set; }
        public string AgreementNumber { get; set; }
        public Nullable<decimal> AgreementPrice { get; set; }
        public Nullable<System.DateTime> dt_agreement { get; set; }
        public Nullable<System.DateTime> dt_effective { get; set; }
        public Nullable<System.DateTime> dt_expiry { get; set; }
        public int modification_um { get; set; }
        public bool isDelete { get; set; }
        public Nullable<System.DateTime> dt_created { get; set; }
        public Nullable<int> created_ID { get; set; }
        public Nullable<System.DateTime> dt_last_updated { get; set; }
        public Nullable<int> last_updated_ID { get; set; }
        public Nullable<System.Guid> RowGuid { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
    
}
