//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SAL.EFLib
{
    public partial class Attachment_ImageThumbNail
    {
        public int row_id { get; set; }
        public Nullable<int> Attachment_ID { get; set; }
        public byte[] ThumbNail { get; set; }
        public Nullable<System.Guid> RowGuid { get; set; }
    }
    
}
