//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SAL.EFLib
{
    public partial class Attachment
    {
        public int row_id { get; set; }
        public string par_obj_name { get; set; }
        public Nullable<int> par_obj_ID { get; set; }
        public string Category_CD { get; set; }
        public string FileType_CD { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public bool isDelete { get; set; }
        public Nullable<System.DateTime> dt_created { get; set; }
        public Nullable<int> created_UID { get; set; }
        public Nullable<System.DateTime> dt_last_updated { get; set; }
        public Nullable<int> last_updated_UID { get; set; }
        public int modification_um { get; set; }
        public Nullable<System.Guid> RowGuid { get; set; }
    }
    
}
