//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SAL.EFLib
{
    public partial class Contact
    {
        public int ROW_ID { get; set; }
        public string ContactName { get; set; }
        public string Type_CD { get; set; }
        public string Title_CD { get; set; }
        public Nullable<int> address_ID { get; set; }
        public string par_obj_name { get; set; }
        public Nullable<int> par_obj_ID { get; set; }
        public string Phone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string BestContactMethod { get; set; }
        public string Comments { get; set; }
        public bool isDelete { get; set; }
        public Nullable<System.DateTime> dt_created { get; set; }
        public Nullable<int> created_by_ID { get; set; }
        public Nullable<System.DateTime> dt_last_updated { get; set; }
        public Nullable<int> last_updated_ID { get; set; }
        public int modification_um { get; set; }
        public Nullable<System.Guid> RowGuid { get; set; }
    }
    
}
