//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SAL.EFLib
{
    public partial class Customer
    {
        public Customer()
        {
            this.Agreements = new HashSet<Agreement>();
            this.Sites = new HashSet<Site>();
        }
    
        public int row_id { get; set; }
        public string BusinessName { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string Comments { get; set; }
        public bool isDelete { get; set; }
        public Nullable<System.DateTime> dt_created { get; set; }
        public Nullable<int> created_by_ID { get; set; }
        public Nullable<System.DateTime> dt_last_updated { get; set; }
        public Nullable<int> last_updated_ID { get; set; }
        public int modification_um { get; set; }
        public Nullable<int> address_id { get; set; }
        public Nullable<int> PrimaryContactID { get; set; }
        public Nullable<System.Guid> RowGuid { get; set; }
        public Nullable<int> BillAddress_id { get; set; }
        public string business_type_cd { get; set; }
        public string status_cd { get; set; }
    
        public virtual ICollection<Agreement> Agreements { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
    }
    
}
