//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SAL.EFLib
{
    public partial class EquipmentType
    {
        public int row_id { get; set; }
        public Nullable<int> EquipmentCategoryID { get; set; }
        public string TemplateName { get; set; }
        public Nullable<int> TeggEquipCode { get; set; }
        public string TagPrefix { get; set; }
        public Nullable<bool> isMediumVoltage { get; set; }
        public Nullable<bool> isPanel { get; set; }
        public Nullable<bool> isRelay { get; set; }
        public Nullable<bool> isContainOil { get; set; }
        public Nullable<decimal> ReplacementCost { get; set; }
        public Nullable<decimal> PremiumFactor { get; set; }
        public Nullable<bool> isDefaultColor { get; set; }
        public bool isDelete { get; set; }
        public Nullable<System.DateTime> dt_created { get; set; }
        public Nullable<int> created_by_ID { get; set; }
        public Nullable<System.DateTime> dt_last_updated { get; set; }
        public Nullable<int> last_updated_ID { get; set; }
        public int modification_um { get; set; }
        public Nullable<System.Guid> RowGuid { get; set; }
        public string category_cd { get; set; }
        public Nullable<int> Merge_to_ID { get; set; }
    }
    
}
