//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SAL.EFLib
{
    public partial class Equipment
    {
        public Equipment()
        {
            this.SiteVisitEquipment_Problems = new HashSet<SiteVisitEquipment_Problems>();
            this.SiteVisitTaskings = new HashSet<SiteVisitTasking>();
        }
    
        public int row_id { get; set; }
        public Nullable<int> parent_ID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> EquipmentTypeID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public string Asset_ID { get; set; }
        public string Description { get; set; }
        public string SerialNumber { get; set; }
        public string Application { get; set; }
        public string SafetyNotes { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public Nullable<bool> flg_Energized { get; set; }
        public Nullable<bool> isCritical { get; set; }
        public Nullable<int> NPVolts { get; set; }
        public Nullable<bool> isStartLoop { get; set; }
        public Nullable<bool> isContainer { get; set; }
        public bool isDelete { get; set; }
        public Nullable<System.DateTime> dt_created { get; set; }
        public Nullable<int> created_by_ID { get; set; }
        public Nullable<System.DateTime> dt_last_updated { get; set; }
        public Nullable<int> last_updated_ID { get; set; }
        public Nullable<System.Guid> RowGuid { get; set; }
        public int modification_um { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual ICollection<SiteVisitEquipment_Problems> SiteVisitEquipment_Problems { get; set; }
        public virtual ICollection<SiteVisitTasking> SiteVisitTaskings { get; set; }
    }
    
}
