//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SAL.EFLib
{
    public partial class QuickLinkLog
    {
        public int row_id { get; set; }
        public Nullable<int> SiteVisit_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<System.DateTime> dt_sent { get; set; }
        public Nullable<System.DateTime> dt_expiry { get; set; }
        public string verification_code { get; set; }
        public int times_login { get; set; }
        public string login_ip { get; set; }
        public string login_name { get; set; }
        public Nullable<System.DateTime> dt_created { get; set; }
        public Nullable<System.DateTime> dt_last_updated { get; set; }
    }
    
}
