//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace SAL.EFLib
{
    public partial class SALEntities : DbContext
    {
        public SALEntities()
            : base("name=SALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Agreement> Agreements { get; set; }
        public DbSet<Attachment> Attachments { get; set; }
        public DbSet<Attachment_ImageThumbNail> Attachment_ImageThumbNail { get; set; }
        public DbSet<Attribute_Template> Attribute_Template { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Equipment> Equipments { get; set; }
        public DbSet<Equipment_InstallationAttributeValues> Equipment_InstallationAttributeValues { get; set; }
        public DbSet<EquipmentCategory> EquipmentCategories { get; set; }
        public DbSet<EquipmentType> EquipmentTypes { get; set; }
        public DbSet<EquipmentType_Attribute> EquipmentType_Attribute { get; set; }
        public DbSet<Form_Template> Form_Template { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<Manufacturer> Manufacturers { get; set; }
        public DbSet<Model> Models { get; set; }
        public DbSet<Problem_Template> Problem_Template { get; set; }
        public DbSet<QuickLinkLog> QuickLinkLogs { get; set; }
        public DbSet<Site> Sites { get; set; }
        public DbSet<Site_RevisitSchedule> Site_RevisitSchedule { get; set; }
        public DbSet<SiteVisit> SiteVisits { get; set; }
        public DbSet<SiteVisitAssignment> SiteVisitAssignments { get; set; }
        public DbSet<SiteVisitEquipment> SiteVisitEquipments { get; set; }
        public DbSet<SiteVisitEquipment_Attributes> SiteVisitEquipment_Attributes { get; set; }
        public DbSet<SiteVisitEquipment_Problems> SiteVisitEquipment_Problems { get; set; }
        public DbSet<SiteVisitEquipment_WorkLog> SiteVisitEquipment_WorkLog { get; set; }
        public DbSet<SiteVisitSchedule> SiteVisitSchedules { get; set; }
        public DbSet<SiteVisitTasking> SiteVisitTaskings { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Task_Template> Task_Template { get; set; }
        public DbSet<TaskTemplate_x_AttributeTemplate> TaskTemplate_x_AttributeTemplate { get; set; }
        public DbSet<tblLOV> tblLOVs { get; set; }
        public DbSet<tblLOV_Category> tblLOV_Category { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<User_role> User_role { get; set; }
    }
}
