//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SAL.EFLib
{
    public partial class Site
    {
        public Site()
        {
            this.Equipments = new HashSet<Equipment>();
            this.Locations = new HashSet<Location>();
            this.SiteVisits = new HashSet<SiteVisit>();
        }
    
        public int ROW_ID { get; set; }
        public string SiteName { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string website { get; set; }
        public Nullable<int> SalesRepID { get; set; }
        public Nullable<int> PrimaryContactID { get; set; }
        public string SiteStatusCD { get; set; }
        public Nullable<int> FacilitySize { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public Nullable<int> SystemAge { get; set; }
        public bool isDelete { get; set; }
        public Nullable<System.DateTime> dt_created { get; set; }
        public Nullable<int> created_by_ID { get; set; }
        public Nullable<System.DateTime> dt_last_updated { get; set; }
        public Nullable<int> last_updated_ID { get; set; }
        public int modification_um { get; set; }
        public string SiteComment { get; set; }
        public Nullable<int> BillAddress_ID { get; set; }
        public Nullable<System.Guid> RowGuid { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Equipment> Equipments { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<SiteVisit> SiteVisits { get; set; }
    }
    
}
