//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SAL.EFLib
{
    public partial class SiteVisit
    {
        public int row_id { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<int> AgreementID { get; set; }
        public string JobNumber { get; set; }
        public string statusCD { get; set; }
        public string JobType_cd { get; set; }
        public Nullable<System.DateTime> dt_start_exp { get; set; }
        public Nullable<System.DateTime> dt_complete_exp { get; set; }
        public Nullable<System.DateTime> dt_start_act { get; set; }
        public Nullable<System.DateTime> dt_complete_act { get; set; }
        public string flg_Plan { get; set; }
        public string SpecialInstruction { get; set; }
        public bool isDelete { get; set; }
        public Nullable<System.DateTime> dt_created { get; set; }
        public Nullable<int> created_by_ID { get; set; }
        public Nullable<System.DateTime> dt_last_updated { get; set; }
        public Nullable<int> last_updated_ID { get; set; }
        public Nullable<System.Guid> RowGuid { get; set; }
    
        public virtual Site Site { get; set; }
    }
    
}
