//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SAL.EFLib
{
    public partial class SiteVisitEquipment_Problems
    {
        public int row_id { get; set; }
        public Nullable<int> SiteVisitEquipmentID { get; set; }
        public string ProblemCategoryCD { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<bool> isImmediateHazard { get; set; }
        public string HazardOptions { get; set; }
        public Nullable<bool> isCustomerNotifiedImmediate { get; set; }
        public string ConsequenceOptions { get; set; }
        public string ConsequenceComment { get; set; }
        public string RecommendationOptions { get; set; }
        public string RecommendationComment { get; set; }
        public string FixOptions { get; set; }
        public string fix_Comments { get; set; }
        public Nullable<bool> isEstimateRequired { get; set; }
        public Nullable<bool> isProblemCorrected { get; set; }
        public Nullable<System.DateTime> dt_problemFound { get; set; }
        public Nullable<System.DateTime> dt_corrected { get; set; }
        public string standard { get; set; }
        public string section { get; set; }
        public string SeverityCD { get; set; }
        public int modification_um { get; set; }
        public bool isDelete { get; set; }
        public Nullable<System.DateTime> dt_created { get; set; }
        public Nullable<int> created_by_ID { get; set; }
        public Nullable<System.DateTime> dt_last_updated { get; set; }
        public Nullable<int> last_updated_ID { get; set; }
        public Nullable<System.Guid> RowGuid { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
    
}
