//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SAL.EFLib
{
    public partial class User
    {
        public int ROW_ID { get; set; }
        public string LoginName { get; set; }
        public string password { get; set; }
        public string Domain_IP { get; set; }
        public string DisplayName { get; set; }
        public string Company { get; set; }
        public string Email { get; set; }
        public string UserType_CD { get; set; }
        public string ROLES { get; set; }
        public Nullable<System.DateTime> dt_expiry { get; set; }
        public string status_flg { get; set; }
        public Nullable<System.DateTime> dt_created { get; set; }
        public Nullable<int> created_UID { get; set; }
        public Nullable<System.DateTime> dt_last_updated { get; set; }
        public Nullable<int> last_updated_UID { get; set; }
        public int modification_um { get; set; }
        public Nullable<System.Guid> RowGuid { get; set; }
    }
    
}
