//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SAL.EFLib
{
    public partial class User_role
    {
        public int row_id { get; set; }
        public string role_code { get; set; }
        public string role_name { get; set; }
        public Nullable<short> role_index { get; set; }
        public string note { get; set; }
        public System.DateTime dt_created { get; set; }
        public string created_by { get; set; }
        public System.DateTime dt_last_updated { get; set; }
        public string last_updated_by { get; set; }
        public short modification_num { get; set; }
        public Nullable<System.Guid> RowGuid { get; set; }
    }
    
}
